# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if any) and other config files
COPY package.json tsup.config.ts ./

# Copy source files
COPY src ./src
COPY tsconfig.json ./

# Install dependencies (ignoring scripts to avoid issues)
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Expose no ports as MCP uses stdio

# Command to run the MCP server
CMD ["node", "dist/index.js"]
